name: Deploy proyecto to digital ocean


on:
  push:
    branches:
      - develop

deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_IP: ${{ secrets.DIGITAL_OCEAN_IP }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
          cd /home/desasolun/Documents/suCarnetOnline/su-carnet-onlineBE
          git pull origin develop
          npm install
          npm run build
          pm2 restart su-carnet-onlineBE
        EOF
