name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: conect to server
      run: ssh -o StrictHostKeyChecking=no desasolun@${{ secrets.DIGITAL_OCEAN_IP }}
    - name: ubicar proyecto
      run: cd /home/desasolun/Documents/suCarnetOnline/su-carnet-onlineBE
    - name: actualizar repositorio
      run: git pull origin develop
    - name: instalar dependencias
      run: yarn
    - name: construir proyecto
      run: yarn run build
    - name: reiniciar manejador de procesos node
      run: pm2 restart su-carnet-onlineBE
